#ifndef STROKE_H
#define STROKE_H

enum STROKE {
    STROKE_SPACE,
    STROKE_DOT,
    STROKE_LEFT_BRACKET,
    STROKE_RIGHT_BRACKET,
    STROKE_0,
    STROKE_2,
    STROKE_3,
    STROKE_PART_OF_4,
    STROKE_PART_OF_5,
    STROKE_6,
    STROKE_PART_OF_7,
    STROKE_8,
    STROKE_9,
    STROKE_VERTICAL_LINE,
    STROKE_HORIZONTAL_LINE,
    STROKE_SLASH,
    STROKE_BACK_SLASH
};

#endif