#ifndef CALCULATOR_PHASE_H
#define CALCULATOR_PHASE_H

enum CALCULATOR_PHASE {
    CALCULATOR_PHASE_FOMULA_FIRST_INPUT,
    CALCULATOR_PHASE_CHILD_FOMULA_FIRST_INPUT,
    CALCULATOR_PHASE_OPERATOR_INPUT,
    CALCULATOR_PHASE_OPERAND_INPUT
};

#endif