#ifndef LITERAL_H
#define LITERAL_H

enum LITERAL {
    LITERAL_0,
    LITERAL_1,
    LITERAL_2,
    LITERAL_3,
    LITERAL_4,
    LITERAL_5,
    LITERAL_6,
    LITERAL_7,
    LITERAL_8,
    LITERAL_9,
    LITERAL_PLUS,
    LITERAL_MINUS,
    LITERAL_MULTIPLY,
    LITERAL_DIVIDE,
    LITERAL_EQUAL,
    LITERAL_LEFT_BRACKET,
    LITERAL_RIGHT_BRACKET,
    LITERAL_DOT,
    LITERAL_UNKNOWN
};

#endif